### ISSUE TITLE
RNN

### ISSUE THREAD

**Issue by DavidHuang0621** [QMIND-Team/educate-jupyterLab#12]
Branch: RNN
Link: Deep Learning/ Recurrent Neural Networks.ipynb

**Comment by uGokalp** [comment]
Hello David,

Thank you for submitting your notebook. I've found that:

- The images you reference in the notebook are missing.
- The sentence "For more on backpropagation and the cost function see ...."  is incomplete. (Under the 4th header - Backpropagation through time)

I've updated your notebook with the Qmind banner and minor formatting fixes.
